### ISSUE TITLE
ConnectedComponent

### ISSUE THREAD

**Issue by dmitry-zaets** [gaearon/react-redux#20]
Is there a way to create a class which will be a base class for Smart Components, instead of using `export default connect(select)(CounterContainer);`?

So it would looks like:
```javascript
export default CounterContainer extends ConnectedComponent {
  select(state) {
    return {
      counter: state.counter
    };
  }
  render() {
    const { dispatch, counter } = this.props;
    return (
      <Counter counter={counter}
               increment={() => dispatch(increment())} />
  );
}
```
I'm not sure, probably it is not possible to implement connector as a base class or that is not a right  way of how it should be done in javascript.

**Comment by gaearon** [comment]
Inheritance is discouraged in React code and should always be avoided for components. Composition solves the same problem in a way that is much easier to maintain.

Consider this:

1) You'd have to remember to call `super` from lifecycle hooks, or component would break in a weird way.

2) If React Redux starts to use a new lifecycle hook in its internal implementation, your existing code might break even if it worked before, because you might have been forgetting to call `super`. 

3)

**Comment by dmitry-zaets** [comment]
Thanks for a good explanation! Will avoid using it in such way!
Just wanted to make using of connectors more transparent than 'connector(select)(Component)' calls.

**Comment by gaearon** [comment]
If you want a neater syntax you can use ES7 decorators proposal implemented by Babel.
Note that it's experimental and may change.

```js
@connect(select)
export default class MyComponent { }
```

**Comment by dmitry-zaets** [comment]
Thanks, I've already noticed that in examples, but still want to avoid using experimental ES7 parts.

**Comment by gaearon** [comment]
A few more comments on React, inheritance and composition:

https://github.com/facebook/react/issues/613#issuecomment-29280175
https://github.com/facebook/react/issues/613#issuecomment-76584019
https://github.com/facebook/react/issues/613#issuecomment-76621639
