### ISSUE TITLE
Add ownProps to mapStateToProps and mapDispatchToProps as second parameter

### ISSUE THREAD

**Issue by gaearon** [gaearon/react-redux#52]
It should only be passed if `fn.length > 1` as per https://github.com/gaearon/react-redux/pull/36#issuecomment-129945686.

If you want to make a PR, please write here so we don't duplicate effort.

**Comment by gaearon** [comment]
Important note: if `mapDispatchToProps.length < 2`, `mapDispatchToProps` should not be called on prop change.

Similarly, if `mapStateToProps.length < 2` or `mergeProps.length < 3`, `componentWillReceiveProps` should not result in their recalculation, respectively.

**Comment by gaearon** [comment]
cc @jhollingworth, @danharper, @ForbesLindesay who wanted to make this happen

**Comment by jhollingworth** [comment]
Happy to implement this if no one else is

**Comment by gaearon** [comment]
Feel free to!

**Comment by PSpSynedra** [comment]
@gaeron What is the current state of this issue? 
We were just updating to redux 1.0.x and have serious problems with props not being available to mapStateToProps. The reason is that we pass memoized selector functions via props that select the desired childProperties from the state. 
As a workaround we could select the whole state and thus have it passed to the mergeProps callback. The problem using this workaround is, that the potentionally expensive mergeProps becomes the mapStateToProps and is callled much to often (the recomputeState is actually called for every state change in the redux store, no matter what part of the state was influenced by the change).

**Comment by theaqua** [comment]
@PSpSynedra https://github.com/gaearon/react-redux/pull/59#issuecomment-131764832

**Comment by PSpSynedra** [comment]
@theaqua, Yeah I just saw it :-) Looking forward to it already.

**Comment by gaearon** [comment]
Released in 0.9.0, please verify.
