### ISSUE TITLE
Link or router.transitionTo or router.replaceWith doesn't work me

### ISSUE THREAD

**Issue by ghondar** [gaearon/react-redux#58]
can i do this?
```javascript
import React from 'react'
import { RouteHandler } from 'react-router'
import { connect } from 'react-redux'
import { setUser } from '../actions/usuarioActions'

@connect()
export default class Root extends React.Component{
  componentDidMount(){
    if(this.props.validate) {
      this.props.dispatch(setUser(this.props.validate))
    }
  }
  render(){
    return (
      <RouteHandler {...this.props} /> 
    )
  }
}
```
because when i click on Link or use replaceWith from router, just change the url but not the component.

**Comment by gaearon** [comment]
Yes, you can definitely do this. If something doesn't work please post a reproducible example.

**Comment by gaearon** [comment]
For start, you can look into https://github.com/gaearon/react-redux#troubleshooting

**Comment by ghondar** [comment]
Thanks for your quick response, here is an example of the error:

https://github.com/ghondar/reduxExample

**Comment by ghondar** [comment]
@gaearon Thanks for your quick response, here is an example of the error:

https://github.com/ghondar/reduxExample

**Comment by gaearon** [comment]
Thanks, but I don't understand how to run this example. :-(
It enters an infinite redirect loop for me.

**Comment by ghondar** [comment]
oh @gaearon i'm sorry, I forgot to put in the readme that port open in the browser u.u.

open http://localhost:3000/

**Comment by gaearon** [comment]
I took a look, it's the thing I posted a link to above.
To be more specific: https://github.com/gaearon/react-redux#my-views-arent-updating-on-route-change-with-react-router-013

The problem is `react-engine` doesn't pass router state as a prop. Therefore `shouldComponentUpdate` check in `react-redux` bails out.

We won't remove this bailout. Please either use React Router vanilla API, or persuade React Engine to pass the router state. For example, this code in `react-engine/lib/client.js`:

```js
    router.run(function onRouterRun(Component) {
      // create a component instance
      var componentInstance = React.createElement(Component, props);
```

can be changed to:

```js
    router.run(function onRouterRun(Component, routerState) {
      // create a component instance
      var componentInstance = React.createElement(Component, Object.assign({}, props, { routerState }));
```

and then it works.

**Comment by ghondar** [comment]
nice @gaearon it works, thank for all :D
